from abc import ABC, abstractmethod
from typing import Any

from loguru import logger
from pydantic import BaseModel, Field

from backend.core.capabilities import capability_registry


class AgentExecutionResult(BaseModel):
    """
    Standardized payload schema for agent run results.
    """

    success: bool = Field(..., description="Flag indicating if the agent completed successfully.")
    output_content: str = Field(
        ..., description="The textual output or report generated by the agent."
    )
    metrics: dict[str, Any] = Field(
        default_factory=dict, description="Operational telemetry counters."
    )
    error_message: str | None = Field(None, description="Detailed error logs if success is False.")


class BaseAgent(ABC):
    """
    Base Agent class that all specialist agents inherit from.
    Integrates with Agno framework parameters and capabilities tracking.
    """

    def __init__(
        self,
        name: str,
        role: str,
        system_instruction: str,
        version: str = "0.1.0",
        tags: list[str] = None,
    ) -> None:
        self.name = name
        self.role = role
        self.system_instruction = system_instruction
        self.version = version
        self.tags = tags or ["agent"]

        # Auto-register this agent's profile in the Capability Registry
        capability_registry.register_capability(
            name=self.name,
            type="agent",
            description=self.role,
            version=self.version,
            tags=self.tags,
            input_schema={"prompt": "string"},
            output_schema=AgentExecutionResult.model_json_schema(),
        )

        logger.info(f"BaseAgent initialized and registered: {self.name}")

    def log_execution_start(self, prompt_len: int) -> None:
        logger.info(
            f"[{self.name}] starting execution cycle. Input prompt length: {prompt_len} chars."
        )

    def log_execution_success(self, output_len: int) -> None:
        logger.info(
            f"[{self.name}] completed execution cycle successfully. Output length: {output_len} chars."
        )

    def log_execution_failure(self, error: str) -> None:
        logger.error(f"[{self.name}] execution cycle failed: {error}")

    @abstractmethod
    async def run(self, prompt: str, **kwargs: Any) -> AgentExecutionResult:
        """
        Abstract runner that concrete agents override to perform executions.
        """
        pass
